### ISSUE TITLE
Gaol compilation fails with "gaol/gaol_flt_output.h" not found

### ISSUE THREAD

**Issue by cyrilbouvier** [goualard-f/GAOL#2]
The current code (commit 6cb21dc58491) of Gaol cannot be compiled due to a failing include:

```
gaol_interval.cpp:54:10: fatal error: gaol/gaol_flt_output.h: No such file or directory
 #include "gaol/gaol_flt_output.h"
```

The file `gaol/gaol_flt_output.h` was deleted by commit 5651b173e7a0314.

If I remove the include line, the compiler raises a another error due to a missing file `bug.cpp`

```
make[1]: *** No rule to make target 'bug.cpp', needed by 'bug.o'.  Stop.
```

**Comment by goualard-f** [comment]
Corrected by commit 1a4cfef on Dec. 15, 2020.
Thanks for the report.
